[platformio]
default_envs = firebeetle2_esp32e
src_dir = src
include_dir = include

[env]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
board_build.partitions = partitions_16MB_ota.csv

build_flags = 
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
    -DARDUINO_RUNNING_CORE=1

lib_deps =
    zinggjm/GxEPD2@^1.5.9
    adafruit/Adafruit GFX Library@^1.11.11
    adafruit/Adafruit AHTX0@^2.0.5
    sciosense/ScioSense_ENS16x@^2.0.4

[env:firebeetle2_esp32e]
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
; upload_port = /dev/ttyUSB1
; monitor_port = /dev/ttyUSB1

[env:firebeetle2_esp32e_ota]
upload_protocol = espota
upload_port = 192.168.1.98
upload_flags =
    --port=3232

