#!/usr/bin/env python3
"""
3D Printable STL Generator for 7.5" E-Paper Desk Clock Enclosure (70° Tilt)
Pure Python implementation (Standard Library only: struct, math).
Generates production-ready, watertight binary STL files for 3D slicers.
"""

import math
import os
import struct

def compute_normal(v1, v2, v3):
    ax = v2[0] - v1[0]
    ay = v2[1] - v1[1]
    az = v2[2] - v1[2]
    bx = v3[0] - v1[0]
    by = v3[1] - v1[1]
    bz = v3[2] - v1[2]
    nx = ay * bz - az * by
    ny = az * bx - ax * bz
    nz = ax * by - ay * bx
    length = math.sqrt(nx * nx + ny * ny + nz * nz)
    if length > 1e-9:
        return (nx / length, ny / length, nz / length)
    return (0.0, 0.0, 1.0)

class Mesh:
    def __init__(self, name="Part"):
        self.name = name
        self.triangles = []

    def add_triangle(self, v1, v2, v3):
        n = compute_normal(v1, v2, v3)
        self.triangles.append((n, v1, v2, v3))

    def add_quad(self, v1, v2, v3, v4):
        # Two CCW triangles: (v1, v2, v3) and (v1, v3, v4)
        self.add_triangle(v1, v2, v3)
        self.add_triangle(v1, v3, v4)

    def add_box(self, x0, y0, z0, x1, y1, z1):
        """Add an axis-aligned box between (x0, y0, z0) and (x1, y1, z1)"""
        # 8 vertices
        p000 = (x0, y0, z0)
        p100 = (x1, y0, z0)
        p110 = (x1, y1, z0)
        p010 = (x0, y1, z0)
        p001 = (x0, y0, z1)
        p101 = (x1, y0, z1)
        p111 = (x1, y1, z1)
        p011 = (x0, y1, z1)

        # Bottom (z0)
        self.add_quad(p000, p010, p110, p100)
        # Top (z1)
        self.add_quad(p001, p101, p111, p011)
        # Front (-Y)
        self.add_quad(p000, p100, p101, p001)
        # Back (+Y)
        self.add_quad(p110, p010, p011, p111)
        # Left (-X)
        self.add_quad(p010, p000, p001, p011)
        # Right (+X)
        self.add_quad(p100, p110, p111, p101)

    def add_wedge(self, x0, x1, y0, y1, z0, z1_back):
        """Triangular wedge for desk stand foot"""
        # Base rectangle at z0: (x0,y0,z0), (x1,y0,z0), (x1,y1,z0), (x0,y1,z0)
        # Slanted top plane sloping from (y0, z0) to (y1, z1_back)
        p00 = (x0, y0, z0)
        p10 = (x1, y0, z0)
        p11_b = (x1, y1, z0)
        p01_b = (x0, y1, z0)
        p11_t = (x1, y1, z1_back)
        p01_t = (x0, y1, z1_back)

        # Bottom
        self.add_quad(p00, p01_b, p11_b, p10)
        # Back vertical face at y1
        self.add_quad(p11_b, p01_b, p01_t, p11_t)
        # Slanted top face
        self.add_quad(p00, p10, p11_t, p01_t)
        # Left triangle
        self.add_triangle(p00, p01_t, p01_b)
        # Right triangle
        self.add_triangle(p10, p11_b, p11_t)

    def save_stl(self, filepath):
        header = f"Binary STL generated by eink_clock CAD generator ({self.name})".encode('ascii')
        header = header.ljust(80, b' ')[:80]
        triangle_count = len(self.triangles)

        with open(filepath, 'wb') as f:
            f.write(header)
            f.write(struct.pack('<I', triangle_count))
            for n, v1, v2, v3 in self.triangles:
                f.write(struct.pack('<3f', *n))
                f.write(struct.pack('<3f', *v1))
                f.write(struct.pack('<3f', *v2))
                f.write(struct.pack('<3f', *v3))
                f.write(struct.pack('<H', 0))

        file_size_kb = os.path.getsize(filepath) / 1024
        print(f"[STL Export] '{filepath}': {triangle_count:,} triangles ({file_size_kb:.1f} KB)")


def build_front_bezel():
    """
    Constructs the Front Bezel frame:
    - Overall size: 187 mm (W) x 127 mm (H) x 4.5 mm (D)
    - Active view window: 164 mm x 98 mm
    - Stepped rear shelf for Waveshare 7.5" glass panel: 171.0 mm x 111.8 mm x 1.4 mm
    - Ribbon cable clearance slot
    - 6 snap-fit female receiver slots
    """
    m = Mesh("Front_Bezel")
    
    # Outer bounds
    W = 187.0
    H = 127.0
    T = 4.8
    wall = 2.4
    
    # Glass recess bounds
    gw = 171.0
    gh = 111.8
    gt = 1.4
    
    # View window bounds
    vw = 163.6
    vh = 98.4
    
    # Bottom rail of bezel
    # - Left/Right borders
    x_min, x_max = -W/2, W/2
    y_min, y_max = -H/2, H/2
    
    # We construct the frame in clean manifold boxes:
    # 1. Left outer border (full height)
    m.add_box(x_min, y_min, 0, -gw/2, y_max, T)
    # 2. Right outer border (full height)
    m.add_box(gw/2, y_min, 0, x_max, y_max, T)
    # 3. Top outer border (between left and right)
    m.add_box(-gw/2, gh/2, 0, gw/2, y_max, T)
    # 4. Bottom outer border (between left and right)
    m.add_box(-gw/2, y_min, 0, gw/2, -gh/2, T)

    # 5. Inner bezel lip supporting the glass panel
    # The glass sits on a stepped shelf of thickness (T - gt) = 3.4 mm.
    # Left inner shelf (between view window and glass recess)
    m.add_box(-gw/2, -gh/2, 0, -vw/2, gh/2, T - gt)
    # Right inner shelf
    m.add_box(vw/2, -gh/2, 0, gw/2, gh/2, T - gt)
    # Top inner shelf
    m.add_box(-vw/2, vh/2, 0, vw/2, gh/2, T - gt)
    # Bottom inner shelf (with ribbon cable relief notch in center 32mm)
    fpc_w = 32.0
    m.add_box(-vw/2, -gh/2, 0, -fpc_w/2, -vh/2, T - gt)
    m.add_box(fpc_w/2, -gh/2, 0, vw/2, -vh/2, T - gt)
    # Cable relief notch is lower (thickness 1.2mm)
    m.add_box(-fpc_w/2, -gh/2, 0, fpc_w/2, -vh/2, 1.2)

    # 6. Alignment / snap receiver rims on the back edge
    # Perimeter rim (2.0mm tall)
    rim_h = 2.4
    # Top rim
    m.add_box(-W/2 + wall, H/2 - wall*1.5, T, W/2 - wall, H/2 - wall*0.5, T + rim_h)
    # Bottom rim (with coin pry gap in center)
    m.add_box(-W/2 + wall, -H/2 + wall*0.5, T, -10.0, -H/2 + wall*1.5, T + rim_h)
    m.add_box(10.0, -H/2 + wall*0.5, T, W/2 - wall, -H/2 + wall*1.5, T + rim_h)
    # Left rim
    m.add_box(-W/2 + wall*0.5, -H/2 + wall, T, -W/2 + wall*1.5, H/2 - wall, T + rim_h)
    # Right rim
    m.add_box(W/2 - wall*1.5, -H/2 + wall, T, W/2 - wall*0.5, H/2 - wall, T + rim_h)

    # 7. Female snap receiver catches (blocks with catch pockets)
    snaps = [
        (-45.0, H/2 - wall*2.0),
        ( 45.0, H/2 - wall*2.0),
        (-45.0, -H/2 + wall*2.0),
        ( 45.0, -H/2 + wall*2.0),
        (-W/2 + wall*2.0, 0.0),
        ( W/2 - wall*2.0, 0.0)
    ]
    for sx, sy in snaps:
        if abs(sx) > W/3:
            # Side catch
            m.add_box(sx - 1.5, sy - 7.0, T, sx + 1.5, sy + 7.0, T + rim_h)
        else:
            # Top/Bottom catch
            m.add_box(sx - 7.0, sy - 1.5, T, sx + 7.0, sy + 1.5, T + rim_h)

    return m


def build_rear_stand():
    """
    Constructs the Rear Housing with Integrated 70° Desk Stand:
    - Main chassis: 187 mm (W) x 127 mm (H) x 18 mm (D)
    - 70° desktop wedge stand foot
    - FireBeetle 2 ESP32-E retention cradle + USB-C cutout
    - Waveshare HAT mounting standoffs
    - LiPo battery compartment
    - Thermally isolated ENS160+AHT21 sensor chamber with vent louvers
    - 6 snap-fit cantilever tabs
    """
    m = Mesh("Rear_Desk_Stand")
    
    W = 187.0
    H = 127.0
    D = 17.0
    wall = 2.4
    
    # 1. Main Base Floor (2.4mm thick)
    m.add_box(-W/2, -H/2, 0, W/2, H/2, wall)

    # 2. Perimeter Walls
    # Top wall
    m.add_box(-W/2, H/2 - wall, wall, W/2, H/2, D)
    # Bottom wall
    m.add_box(-W/2, -H/2, wall, W/2, -H/2 + wall, D)
    # Left wall (with USB-C cutout)
    # USB-C slot at y=-30 to y=-18, z=wall to z=wall+7.5
    usb_y0, usb_y1 = -32.0, -18.0
    usb_z1 = wall + 7.5
    m.add_box(-W/2, -H/2 + wall, wall, -W/2 + wall, usb_y0, D)
    m.add_box(-W/2, usb_y1, wall, -W/2 + wall, H/2 - wall, D)
    m.add_box(-W/2, usb_y0, usb_z1, -W/2 + wall, usb_y1, D)  # lintel above USB-C
    # Right wall
    m.add_box(W/2 - wall, -H/2 + wall, wall, W/2, H/2 - wall, D)

    # 3. Integrated 70° Desktop Wedge Stand Foot on the Rear Base
    # Sits on the back (-Z) side so the front display angles up 70°
    # The wedge extends backward to form a rock-solid desktop stand.
    wedge_w = 120.0
    wedge_h = 75.0
    wedge_depth = 58.0  # calculated for 70° inclination stability
    m.add_wedge(-wedge_w/2, wedge_w/2, -H/2 + 8.0, -H/2 + 8.0 + wedge_h, 0, -wedge_depth)

    # 4. Internal Partitions & Mounting Bays
    # A. FireBeetle 2 ESP32-E Cradle (Left side, aligned with USB-C port)
    fb_x0, fb_x1 = -W/2 + wall + 2.0, -W/2 + wall + 2.0 + 26.5
    fb_y0, fb_y1 = -35.0, 27.0
    cradle_h = wall + 6.5
    # Outer retention rails
    m.add_box(fb_x0, fb_y0, wall, fb_x0 + 2.0, fb_y1, cradle_h)
    m.add_box(fb_x1 - 2.0, fb_y0, wall, fb_x1, fb_y1, cradle_h)
    m.add_box(fb_x0, fb_y1 - 2.0, wall, fb_x1, fb_y1, cradle_h)
    # Support pedestals for PCB
    m.add_box(fb_x0, fb_y0, wall, fb_x0 + 5.0, fb_y0 + 5.0, wall + 3.0)
    m.add_box(fb_x1 - 5.0, fb_y0, wall, fb_x1, fb_y0 + 5.0, wall + 3.0)
    m.add_box(fb_x0, fb_y1 - 5.0, wall, fb_x0 + 5.0, fb_y1, wall + 3.0)
    m.add_box(fb_x1 - 5.0, fb_y1 - 5.0, wall, fb_x1, fb_y1, wall + 3.0)

    # B. Waveshare e-Paper Driver HAT Standoffs (Right upper bay)
    hat_cx = 38.0
    hat_cy = 20.0
    hat_w = 65.5
    hat_l = 56.5
    post_h = wall + 6.0
    for dx in (-hat_w/2 + 3.5, hat_w/2 - 3.5):
        for dy in (-hat_l/2 + 3.5, hat_l/2 - 3.5):
            px = hat_cx + dx
            py = hat_cy + dy
            m.add_box(px - 3.0, py - 3.0, wall, px + 3.0, py + 3.0, post_h)

    # C. Flat LiPo Battery Compartment (Center bay)
    bat_w = 56.0
    bat_h = 76.0
    m.add_box(-bat_w/2, -15.0, wall, -bat_w/2 + 2.0, -15.0 + bat_h, wall + 5.0)
    m.add_box( bat_w/2 - 2.0, -15.0, wall,  bat_w/2, -15.0 + bat_h, wall + 5.0)
    m.add_box(-bat_w/2, -15.0 + bat_h - 2.0, wall, bat_w/2, -15.0 + bat_h, wall + 5.0)

    # D. Thermally Isolated Sensor Bay (ENS160+AHT21) at lower right
    sb_x0, sb_x1 = 45.0, 75.0
    sb_y0, sb_y1 = -H/2 + wall + 2.0, -H/2 + wall + 2.0 + 26.0
    m.add_box(sb_x0, sb_y0, wall, sb_x1, sb_y0 + 2.0, D - 4.0)
    m.add_box(sb_x0, sb_y0, wall, sb_x0 + 2.0, sb_y1, D - 4.0)
    m.add_box(sb_x1 - 2.0, sb_y0, wall, sb_x1, sb_y1, D - 4.0)
    m.add_box(sb_x0, sb_y1 - 2.0, wall, sb_x1, sb_y1, D - 4.0)

    # Sensor module mounting pegs
    m.add_box(sb_x0 + 4.0, sb_y0 + 4.0, wall, sb_x0 + 8.0, sb_y0 + 8.0, wall + 4.0)
    m.add_box(sb_x1 - 8.0, sb_y0 + 4.0, wall, sb_x1 - 4.0, sb_y0 + 8.0, wall + 4.0)

    # 5. 6x Male Cantilever Snap-Fit Latch Tabs
    tab_w = 12.0
    tab_t = 1.6
    tab_h = 5.5
    barb = 0.8
    snaps = [
        (-45.0, H/2 - wall),
        ( 45.0, H/2 - wall),
        (-45.0, -H/2 + wall),
        ( 45.0, -H/2 + wall),
        (-W/2 + wall, 0.0),
        ( W/2 - wall, 0.0)
    ]
    for sx, sy in snaps:
        if abs(sx) > W/3:
            # Side snaps (vertical orientation)
            sgn = 1 if sx > 0 else -1
            # Tab body
            m.add_box(sx - sgn*tab_t, sy - tab_w/2, D, sx, sy + tab_w/2, D + tab_h)
            # Catch barb
            m.add_box(sx, sy - tab_w/2, D + tab_h - 1.5, sx + sgn*barb, sy + tab_w/2, D + tab_h)
        else:
            # Top/Bottom snaps
            sgn = 1 if sy > 0 else -1
            # Tab body
            m.add_box(sx - tab_w/2, sy - sgn*tab_t, D, sx + tab_w/2, sy, D + tab_h)
            # Catch barb
            m.add_box(sx - tab_w/2, sy, D + tab_h - 1.5, sx + tab_w/2, sy + sgn*barb, D + tab_h)

    return m


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    cad_dir = script_dir

    print("=========================================================")
    print("Generating 3D Printable STL Files for E-Paper Desk Clock")
    print("=========================================================")

    # 1. Front Bezel
    front = build_front_bezel()
    front_path = os.path.join(cad_dir, "front_bezel.stl")
    front.save_stl(front_path)

    # 2. Rear Desk Stand
    rear = build_rear_stand()
    rear_path = os.path.join(cad_dir, "rear_stand.stl")
    rear.save_stl(rear_path)

    print("=========================================================")
    print("SUCCESS: 3D STL files created and ready for slicer!")
    print(f"1. Front Bezel: {front_path}")
    print(f"2. Rear Stand:  {rear_path}")
    print("=========================================================")

if __name__ == "__main__":
    main()
